python3 regret_new.py SALUCB hoeffding boundedA bandit
python3 regret_new.py SALUCB hoeffding boundedB bandit
python3 regret_new.py SALUCB hoeffding boundedC bandit
python3 regret_new.py SALUCBSingle hoeffdingSingle boundedA bandit
python3 regret_new.py SALUCBSingle hoeffdingSingle boundedB bandit
python3 regret_new.py SALUCBSingle hoeffdingSingle boundedC bandit
python3 regret_new.py SALUCB lil boundedA bandit
python3 regret_new.py SALUCB lil boundedB bandit
python3 regret_new.py SALUCB lil boundedC bandit
python3 regret_new.py SALUCBSingle lil boundedA bandit
python3 regret_new.py SALUCBSingle lil boundedB bandit
python3 regret_new.py SALUCBSingle lil boundedC bandit
python3 regret_new.py LUAS hoeffding boundedA bandit
python3 regret_new.py LUAS hoeffding boundedB bandit
python3 regret_new.py LUAS hoeffding boundedC bandit
python3 regret_new.py LUAS lil boundedA bandit
python3 regret_new.py LUAS lil boundedB bandit
python3 regret_new.py LUAS lil boundedC bandit
